services:
  app:
    image: ghcr.io/ryu-sato/rss-reader
    ports:
      - "3000:3000"
    volumes:
      - db-data:/app/data
    environment:
      DATABASE_URL: "file:/app/data/db.sqlite"
    env_file:
      - .env.app
    restart: unless-stopped

  tunnel:
    image: cloudflare/cloudflared:latest
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token
      - ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db-data: